### ISSUE TITLE
Debian/Ubuntu Package

### ISSUE THREAD

**Issue by aleneum** [iclcv/icl#1]
Which dependencies should be part of an deb-package? Dependencies should be limited to packages retrievable from official sources (no IPP, libfreenect2) I guess.
I'd suggest to target Ubuntu 16.04 first. What do you think @scires, @celbrech, @guihomework and @rhaschke?

**Comment by guihomework** [comment]
sometimes there are dependencies to packages available in unofficial/ppa but if it can be avoided then the default package would then not build with unofficial sources. 
An example, Blender in ubuntu does not have collada export support because libcollada is not officially released as debian package. Some libcollada can be found and one can find ppa with Blender built with it.

**Comment by rhaschke** [comment]
I agree to limit the deb-package to use default Ubuntu packages only.
